apiVersion: v1
kind: Secret
metadata:
  name: user-svc-helidon-secrets
data:
  dbUser: dXNlcnN2Yw==
  dbPassword: U1BlY3RyYTIwMjBfIw==
  dbUrl: amRiYzpvcmFjbGU6dGhpbjpAc3BlY3RyYWF0cDE5Y190cD9UTlNfQURNSU49L2hlbGlkb24vd2FsbGV0